# Generated by Django 3.2.3 on 2021-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210524_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description1',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
